### ISSUE TITLE
安装插件后，无法发现新实体，解析api.scinan.com失败

### ISSUE THREAD

**Issue by old009** [Yonsm/ZhiSaswell#4]
设备，海林㻏动，在安装插件后，却无法发现新实体，日志如下，麻烦大神指点一下。谢谢！
01:56:36 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zhisaswell which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-17 01:56:46 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform zhisaswell is taking over 10 seconds.
2022-05-17 01:57:36 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: climate.zhisaswell
2022-05-17 01:57:36 ERROR (MainThread) [homeassistant.components.climate] Setup of platform zhisaswell is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-05-17 01:58:44 ERROR (MainThread) [custom_components.zhisaswell.climate] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('180.153.186.236', 80)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/zhisaswell/climate.py", line 185, in update_data
json = await self.request(LIST_URL)
File "/config/custom_components/zhisaswell/climate.py", line 242, in request
async with await session.get(auth_url, headers=headers) as r:
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.scinan.com:80 ssl:default [Connect call failed ('180.153.186.236', 80)]
2022-05-17 01:58:44 ERROR (MainThread) [custom_components.zhisaswell.climate] No sensors added.

看了一下代码，是不是在解析api.scinan.com这个域名的时候出问题了，180.153.186.236这个地址也ping不通

麻烦大神了，谢谢！

**Comment by xia0linz1** [comment]
scinan.com域名是广东司南物联股份有限公司的，估计是个做物联网平台的。
之前域名垮过一次，但这次垮得有点久
