### ISSUE TITLE
插件提示错误信息，无法同步状态

### ISSUE THREAD

**Issue by snareren** [Yonsm/ZhiSaswell#6]
Logger: custom_components.zhisaswell.climate
Source: custom_components/zhisaswell/climate.py:130 
Integration: zhisaswell ([documentation](https://github.com/Yonsm/ZhiSaswell)) 
First occurred: 10:17:39 (3 occurrences) 
Last logged: 10:18:16

Exception: Traceback (most recent call last): File "/config/custom_components/zhisaswell/climate.py", line 224, in control json = await self.request(CTRL_URL % (data, device_id, sensor_id)) File "/config/custom_components/zhisaswell/climate.py", line 260, in request return await r.json(content_type=None) File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json return await super().json(*args, loads=loads, **kwargs) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json return loads(stripped.decode(encoding)) orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

Logger: homeassistant
Source: custom_components/zhisaswell/climate.py:180 
Integration: zhisaswell ([documentation](https://github.com/Yonsm/ZhiSaswell)) 
First occurred: 10:41:49 (2 occurrences) 
Last logged: 10:46:49

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/zhisaswell/climate.py", line 180, in async_update
    await asyncio.wait(tasks, loop=self._hass.loop)
TypeError: wait() got an unexpected keyword argument 'loop'

最近插件一直提示上述信息，可控制开关、温度设置，但无法同步地暖状态，试着对插件进行调整无法解决，还请大神指点。

**Comment by pibunei** [comment]
同问题，可以控制但是ha显示的温控要不就是火的图标的状态或者关机的图标状态，举例，我通过ha开地暖ha显示是火的图标，我通过ha关地暖显示的还是火的图标
